# Variables

pref_dir="$HOME/.prefs"
pref_colors="$pref_dir/colors"
pref_settings="$pref_dir/settings"
pref_darwin="$pref_dir/darwin"
pref_linux="$pref_dir/linux"
pref_python="$pref_dir/python"
pref_virtualenv="$pref_dir/virtualenv"
pref_amazon="$pref_dir/amazon"
pref_aliases="$pref_dir/aliases"
pref_ps1="$pref_dir/ps1"
pref_sublime="$pref_dir/sublime"
pref_rvm="$pref_dir/rvm"

# Other Variables

sys_name=$(uname)
darwin_name="Darwin"

# Create pref array with minimal settings.

prefs=($pref_linux)

# Redefine prefs if we are on OSX (Darwin)
# Using [n] notation for readability
# You can also init array thusly, prefs=($foo $bar $baz)

if [ $sys_name == $darwin_name ]; then
    prefs[0]=$pref_colors
    prefs[1]=$pref_ps1
    prefs[2]=$pref_settings
    prefs[3]=$pref_darwin
    prefs[4]=$pref_python
    prefs[5]=$pref_virtualenv
    prefs[6]=$pref_aliases
    prefs[7]=$pref_sublime
    prefs[8]=$pref_rvm
fi


# Load prefs
# echo "Loading Prefs:"

for pref in "${prefs[@]}"
do
    if [ -f $pref ]; then
        source $pref
    fi
done
